grid:
  - ["SNOWY_TAIGA", "SNOWY_TAIGA", "SNOWY_TAIGA", "TUNDRA", "TUNDRA", "TUNDRA", "TUNDRA",  "COLD_BEACH", "FROZEN_OCEAN", "COLD_OCEAN", "COLD_OCEAN"]
  - ["SNOWY_TAIGA", "SNOWY_TAIGA", "SNOWY_TAIGA", "TUNDRA", "TUNDRA", "TUNDRA", "TUNDRA",  "COLD_BEACH", "FROZEN_OCEAN", "COLD_OCEAN", "COLD_OCEAN"]
id: COLD