grid:
  - ["TAIGA", "TAIGA", "TAIGA", "TUNDRA", "TUNDRA", "TUNDRA", "TUNDRA",  "COLD_BEACH", "FROZEN_OCEAN", "COLD_OCEAN", "COLD_OCEAN"]
  - ["TAIGA", "TAIGA", "TAIGA", "TUNDRA", "TUNDRA", "TUNDRA", "TUNDRA",  "COLD_BEACH", "FROZEN_OCEAN", "COLD_OCEAN", "COLD_OCEAN"]
id: COLD
name: "Cold Grid"