grid:
  - ["MOUNTAINS_PRETTY_0", "MOUNTAINS_PRETTY_0", "MOUNTAINS_PRETTY_0", "MOUNTAINS_PRETTY_0", "MOUNTAINS_PRETTY_0", "MOUNTAINS_PRETTY_0", "MOUNTAINS_PRETTY_0",  "COLD_BEACH", "FROZEN_OCEAN", "COLD_OCEAN", "COLD_OCEAN"]
  - ["MOUNTAINS_PRETTY_0", "MOUNTAINS_PRETTY_0", "MOUNTAINS_PRETTY_0", "MOUNTAINS_PRETTY_0", "MOUNTAINS_PRETTY_0", "MOUNTAINS_PRETTY_0", "MOUNTAINS_PRETTY_0",  "COLD_BEACH", "FROZEN_OCEAN", "COLD_OCEAN", "COLD_OCEAN"]
id: MOUNTAIN_0