id: OVERWORLD
grids:
  - RIDGE_GRID
frequencies:
  grid-x: 1536
  grid-z: 1536
  zone: 2048
blend:
  enable: true
  frequency: 0.125
  amplitude: 10
erode:
  enable: false
  frequency: 0.002
  threshold: 0.00125
  grid: "BIOME:RIVER"
