id: OVERWORLD
grids:
  - OCEAN
  - OCEAN
  - OCEAN
  - OCEAN
  - OCEAN
  - OCEAN
  - OCEAN
  - OCEAN
  - OCEAN
  - OCEAN
  - OCEAN
  - BEACH
  - LAND
  - LAND
  - LAND
  - LAND
  - LAND
  - LAND
  - LAND
  - LAND
  - LAND
  - LAND
  - LAND
  - LAND
  - MOUNTAIN_0
  - MOUNTAIN_1
  - MOUNTAIN
  - MOUNTAIN
  - MOUNTAIN
  - MOUNTAIN
  - MOUNTAIN
  - MOUNTAIN
sea-level: 63
biome-resolution: 4
frequencies:
  grid-x: 1536
  grid-z: 1536
  zone: 2048
blend:
  enable: true
  frequency: 0.125
  amplitude: 10
erode:
  enable: true
  frequency: 0.002
  threshold: 0.00125
  grid: "BIOME:RIVER"
