id: OVERWORLD
grids:
  - TROPICAL
  - TROPICAL
  - TROPICAL
  - TROPICAL
  - TROPICAL
  - TROPICAL
  - TROPICAL
  - RIVER_TROPIC
  - TEMPERATE
  - TEMPERATE
  - TEMPERATE
  - TEMPERATE
  - TEMPERATE
  - TEMPERATE
  - TEMPERATE
  - TEMPERATE
  - TEMPERATE
  - TEMPERATE
  - RIVER
  - COLD_EDGE
  - COLD_EDGE
  - COLD
  - COLD
  - COLD
  - COLD
  - COLD
  - MOUNTAIN_0
  - MOUNTAIN_0
  - MOUNTAIN_1
  - MOUNTAIN_1
  - MOUNTAIN
  - MOUNTAIN
  - MOUNTAIN
  - MOUNTAIN
  - MOUNTAIN
  - MOUNTAIN
  - MOUNTAIN
sea-level: 63
biome-resolution: 4
frequencies:
  grid-x: 512
  grid-z: 1024
  zone: 3072
blend:
  enable: true
  frequency: 0.125
  amplitude: 10
  ignore-terrain: true
