blocks:
  - materials:
      - "minecraft:cobblestone_stairs": 1
      - "minecraft:stone_stairs": 3
    layers: 1
id: MOUNTAIN_STAIRS
name: "Mountain Stairs palette"
simplex: true
frequency: 0.1
seed: 4