noise-equation: "abs(y-64)/96 + noise3(x*3, y*4, z*3)*2"
id: "SOUL_VALLEY"
extends: "NETHER"
flora-chance: 2
flora-attempts: 1
flora:
  BLUE_FIRE:
    weight: 5
    y:
      min: 1
      max: 255
  BASALT:
    weight: 1
    y:
      min: 1
      max: 255
ocean:
  level: 32
  palette: "BLOCK:minecraft:lava"
palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - SOUL: 251
  - BEDROCK: 255
  - BEDROCK_MOST: 254
  - BEDROCK_HALF: 253
  - BEDROCK_LITTLE: 252
vanilla: SOUL_SAND_VALLEY