noise-equation: "if(y, abs(y-64)/128 + noise3(x*1.5, y*2, z*1.5)*3, 1)"
id: "DELTA"
extends: "NETHER"
flora-chance: 60
flora-attempts: 1
flora-simplex:
  enable: true
  frequency: 0.1
  seed: 4
flora:
  BASALT:
    weight: 49
    y:
      min: 1
      max: 255
  LAVA:
    weight: 1
    y:
      min: 1
      max: 255
ocean:
  level: 32
  palette: "BLOCK:minecraft:lava"
palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - DELTA: 251
  - BEDROCK: 255
  - BEDROCK_MOST: 254
  - BEDROCK_HALF: 253
  - BEDROCK_LITTLE: 252
vanilla: BASALT_DELTAS