extends: "NETHER"
id: "NETHER"
name: "Nether"
flora-chance: 60
flora-attempts: 2
flora:
  FIRE:
    weight: 1
    y:
      min: 1
      max: 255
ocean:
  level: 32
  palette: "BLOCK:minecraft:lava"
palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - NETHER: 251
  - BEDROCK: 255
  - BEDROCK_MOST: 254
  - BEDROCK_HALF: 253
  - BEDROCK_LITTLE: 252
vanilla: NETHER_WASTES

