noise-equation: "if(y, abs(y-64)/128 + noise3(x*1.5, y*3, z*1.5)*2, 1)"
id: "SOUL_VALLEY"
extends: "NETHER"
flora:
  chance: 2
  attempts: 1
  items:
    BLUE_FIRE:
      weight: 5
      y:
        min: 1
        max: 255
    BASALT:
      weight: 1
      y:
        min: 1
        max: 255
palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - SOUL: 251
  - BEDROCK: 255
  - BEDROCK_MOST: 254
  - BEDROCK_HALF: 253
  - BEDROCK_LITTLE: 252
vanilla: SOUL_SAND_VALLEY