extends: "NETHER"
id: "WARPED"
flora-chance: 1
flora-attempts: 1
flora:
  FIRE:
    weight: 1
    y:
      min: 1
      max: 255
tree-chance: 90
tree-density: 1
trees:
  WARPED_FUNGUS: 1
ocean:
  level: 32
  palette: "BLOCK:minecraft:lava"
palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - WARPED: 251
  - NETHER_GRAVEL: 32
  - BEDROCK_MOST: 254
  - BEDROCK_HALF: 253
  - BEDROCK_LITTLE: 252
vanilla: WARPED_FOREST

