noise-equation: "((-((y / 62)^2)) + 1) + ((noise2(x, z)+0.5) / 3) + max(min(floor(noise3(x, y, z)*12 + noise2(x, z)*22), 18)/10, 0)"
extends: "BASIC_ORES"
id: "MESA"
name: "Mesa"

palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - RED_DESERT: 255
  - "BLOCK:minecraft:red_terracotta": 128
  - "BLOCK:minecraft:orange_terracotta": 124
  - "BLOCK:minecraft:terracotta": 120
  - "BLOCK:minecraft:yellow_terracotta": 116
  - "BLOCK:minecraft:red_terracotta": 112
  - "BLOCK:minecraft:orange_terracotta": 108
  - "BLOCK:minecraft:terracotta": 104
  - "BLOCK:minecraft:red_terracotta": 100
  - "BLOCK:minecraft:orange_terracotta": 96
  - "BLOCK:minecraft:terracotta": 92
  - "BLOCK:minecraft:yellow_terracotta": 88
  - "BLOCK:minecraft:red_terracotta": 84
  - "BLOCK:minecraft:orange_terracotta": 80
  - "BLOCK:minecraft:terracotta": 76
  - RED_DESERT: 72
vanilla: BADLANDS

flora-chance: 2
flora:
  DEAD_BUSH:
    weight: 1
    y:
      min: 62
      max: 84
  SMALL_ROCK:
    weight: 1
    y:
      min: 62
      max: 84
slabs:
  enable: true
  threshold: 0.015
  palettes:
    - "minecraft:red_sand": "BLOCK:minecraft:red_sandstone_slab"
  use-stairs-if-available: true
  stair-palettes:
    - "minecraft:red_sand": "BLOCK:minecraft:red_sandstone_stairs"

tree-chance: 50
tree-density: 1
trees:
  CACTUS: 9