noise-equation: "((-((y / 70)^2)) + 1) + ((noise2(x, z)+0.5) / 3) + abs(noise2(x/2, z/2)*4)"
extends: "BASIC_ORES"
id: "MOUNTAINS_PRETTY_1"

palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - MOUNTAIN_PRETTY: 255
vanilla: PLAINS

tree-chance: 15
tree-density: 0
trees:
  "SPRUCE": 1

flora-chance: 60
flora-attempts: 2
flora:
  SMALL_ROCK:
    weight: 1
    y:
      min: 62
      max: 180
  TALL_GRASS:
    weight: 1
    y:
      min: 62
      max: 180
  GRASS:
    weight: 5
    y:
      min: 62
      max: 180
  LEAVES:
    weight: 3
    y:
      min: 62
      max: 180
flora-simplex:
  enable: true
  frequency: 0.1
  seed: 4

slabs:
  enable: true
  threshold: 0.015
  palettes:
    - "minecraft:stone": "MOUNTAIN_SLABS"
    - "minecraft:gravel": "MOUNTAIN_SLABS"
  use-stairs-if-available: true
  stair-palettes:
    - "minecraft:stone": "MOUNTAIN_STAIRS"
    - "minecraft:gravel": "MOUNTAIN_STAIRS"