extends: "PLAINS_ABSTRACT"
id: "PLAINS"
name: "Plains"

palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - RIVER_BOTTOM: 61
  - RIVER_SHORE: 62
  - GRASSY: 255
vanilla: PLAINS

flora-chance: 60
flora:
  TALL_GRASS:
    weight: 160
    y:
      min: 62
      max: 84
  GRASS:
    weight: 100
    y:
      min: 62
      max: 84
  SUNFLOWER:
    weight: 8
    y:
      min: 62
      max: 84

tree-chance: 1
tree-density: 0
trees:
  "TERRA:OAK_MEDIUM": 2

# Carving and ores covered by super biome