extends: "RIDGE_ABSTRACT"
id: "RIDGES"

palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - RIDGES: 255
vanilla: SAVANNA

erodible: true

flora:
  chance: 40
  attempts: 1
  items:
    TALL_GRASS:
      weight: 15
      y:
        min: 62
        max: 128
    GRASS:
      weight: 70
      y:
        min: 62
        max: 128

trees:
  chance: 80
  density: 1
  items:
    ACACIA:
      weight: 1
      y:
        min: 58
        max: 128
slabs:
  enable: true
  threshold: 0.015
  palettes:
    - "minecraft:red_sand": "BLOCK:minecraft:red_sandstone_slab"
  use-stairs-if-available: true
  stair-palettes:
    - "minecraft:red_sand": "BLOCK:minecraft:red_sandstone_stairs"
