noise-equation: "((-((y / 62)^2)) + 1) + ((noise2(x, z)+0.5) / 1.5)"
extends: "BASIC_ORES"
id: "TAIGA"
name: "Taiga Forest"

palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - RIVER_BOTTOM: 61
  - RIVER_SHORE: 62
  - TAIGA: 255
vanilla: TAIGA

flora-chance: 40
flora:
  TALL_GRASS:
    weight: 15
    y:
      min: 62
      max: 84
  GRASS:
    weight: 75
    y:
      min: 62
      max: 84
  POPPY:
    weight: 5
    y:
      min: 62
      max: 84

tree-chance: 100
tree-density: 5
trees:
  "SPRUCE": 7
  "LARGE_SPRUCE": 3