extends: "PLAINS_ABSTRACT"
id: "TUNDRA"
name: "Tundra"

palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - TUNDRA: 255
vanilla: SNOWY_TUNDRA
carving:
  - CAVE_TUNDRA: 35
  - RAVINE: 5
  - CAVERN: 5

snow-chance: 20
erodible: true

flora-chance: 2
flora:
  SMALL_ROCK:
    weight: 1
    y:
      min: 60
      max: 255
slabs:
  enable: true
  threshold: 0.015
  palettes:
    - "minecraft:stone": "MOUNTAIN_SLABS"
    - "minecraft:snow_block": "SNOW_LAYERS"
    - "minecraft:gravel": "MOUNTAIN_SLABS"
  use-stairs-if-available: true
  stair-palettes:
    - "minecraft:stone": "MOUNTAIN_STAIRS"
    - "minecraft:gravel": "MOUNTAIN_STAIRS"