blocks:
  - materials:
      - "minecraft:blackstone": 1
      - "minecraft:air": 1
      - "minecraft:basalt": 1
      - "minecraft:air": 1
      - "minecraft:basalt": 1
      - "minecraft:air": 1
      - "minecraft:basalt": 1
      - "minecraft:air": 1
      - "minecraft:basalt": 1
      - "minecraft:air": 1
      - "minecraft:basalt": 1
      - "minecraft:air": 1
      - "minecraft:magma_block": 1
      - "minecraft:air": 1
    layers: 1
  - materials:
      - "minecraft:blackstone": 2
      - "minecraft:basalt": 10
      - "minecraft:magma_block": 2
    layers: 3
  - materials:
      - "minecraft:netherrack": 1
    layers: 1
id: DELTA
simplex: true
frequency: 0.1