blocks:
  - materials:
      - "minecraft:warped_nylium": 49
      - "minecraft:gravel": 1
    layers: 3
  - materials:
      - "minecraft:netherrack": 1
    layers: 1
id: WARPED
simplex: true
frequency: 0.02