extends: "MOUNTAINS_PRETTY_0"
id: "MOUNTAINS_STONE_0"
noise-equation: "((-((y / 64)^2)) + 1) + ((noise2(x, z)+0.5) / 3) + max(noise2(x/2, z/2)*2, 0)"
palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - MOUNTAIN_STONE: 255
  - MOUNTAIN_STONE_GRASS: 108
  - MOUNTAIN_GRASS: 84
vanilla: MOUNTAINS
snow:
  - min: 0
    max: 120
    chance: 50
  - min: 120
    max: 140
    chance: 75
  - min: 140
    max: 255
    chance: 100
trees:
  chance: 100
  density: 4
  items:
    SPRUCE:
      weight: 1
      y:
        min: 58
        max: 92

flora:
  chance: 0
  attempts: 0
  items: {}