files:
  swamp1: 1
  swamp2: 1
  swamp3: 1
  swamp4: 1
  swamp5: 1
  swamp6: 1
  swamp7: 1
  swamp8: 1
id: "SWAMP"
spawn:
  start:
    min: 64
    max: 64
  bound:
    min-y: 48
    max-y: 72
  type: DISTRIBUTE
  width: 75
  padding: 25
  search: DOWN
group:
  enable: true
  size:
    min: 3
    max: 5
  distribution:
    radius: 20
    distance-min: 8

