files:
  swamp1: 1
  swamp2: 1
  swamp3: 1
  swamp4: 1
  swamp5: 1
  swamp6: 1
  swamp7: 1
  swamp8: 1
id: "SWAMP"
spawn:
  start:
    min: 72
    max: 72
  bound:
    min-y: 48
    max-y: 72
  type: DISTRIBUTE
  width: 75
  padding: 25
  search: DOWN