extends: "BEACH_ABSTRACT"
id: "COLD_BEACH"
name: "Cold Beach"
palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - GRAVEL: 64
  - TUNDRA: 255

vanilla: SNOWY_BEACH
ocean:
  palette: "COLD_OCEAN"
  level: 62