blocks:
  - materials:
      - "minecraft:kelp": 1
    layers: 1
  - materials:
      - "minecraft:kelp_plant": 1
    layers: 9

id: KELP_TALL
name: "Tall Kelp"
spawnable:
  - "minecraft:sand"
  - "minecraft:stone"
  - "minecraft:red_sand"
  - "minecraft:gravel"
  - "minecraft:dirt"
replaceable:
  - "minecraft:water"