grid:
  - ["MOUNTAINS_PRETTY", "MOUNTAINS_PRETTY", "TUNDRA", "TUNDRA", "TUNDRA", "TUNDRA", "COLD_BEACH",  "COLD_OCEAN", "COLD_OCEAN", "COLD_OCEAN", "COLD_OCEAN"]
  - ["MOUNTAINS_PRETTY", "MOUNTAINS_PRETTY", "MOUNTAINS_PRETTY", "MOUNTAINS_PRETTY", "MOUNTAINS_PRETTY", "TUNDRA", "COLD_BEACH",  "COLD_OCEAN", "COLD_OCEAN", "COLD_OCEAN", "COLD_OCEAN"]
id: COLD
name: "Cold Grid"