grid:
  - ["MOUNTAINS", "MOUNTAINS", "TUNDRA", "TUNDRA", "TUNDRA", "TUNDRA", "COLD_BEACH",  "COLD_OCEAN", "COLD_OCEAN", "COLD_OCEAN", "COLD_OCEAN"]
  - ["MOUNTAINS", "MOUNTAINS", "MOUNTAINS", "MOUNTAINS", "MOUNTAINS", "TUNDRA", "COLD_BEACH",  "COLD_OCEAN", "COLD_OCEAN", "COLD_OCEAN", "COLD_OCEAN"]
id: COLD
name: "Cold Grid"