grid:
  - ["MESA","MESA","MESA","MESA", "MESA_BORDER", "DESERT", "DESERT", "DESERT", "DESERT", "DESERT", "DESERT", "DESERT", "WARM_BEACH", "WARM_BEACH", "WARM_OCEAN", "WARM_OCEAN", "WARM_OCEAN", "WARM_OCEAN", "WARM_OCEAN", "WARM_OCEAN"]
id: DESERT
name: "Desert Grid"