grid:
  - ["OAK_FOREST", "OAK_FOREST", "OAK_FOREST", "BIRCH_FOREST", "SAVANNA", "SAVANNA", "BEACH", "WARM_OCEAN", "WARM_OCEAN", "WARM_OCEAN"]
  - ["OAK_FOREST", "OAK_FOREST", "OAK_FOREST", "BIRCH_FOREST", "SAVANNA", "SAVANNA", "BEACH", "WARM_OCEAN", "WARM_OCEAN", "WARM_OCEAN"]
  - ["TAIGA", "TAIGA", "PLAINS", "PLAINS", "PLAINS", "PLAINS", "BEACH", "OCEAN", "OCEAN", "OCEAN"]
  - ["TAIGA", "TAIGA", "PLAINS", "PLAINS", "PLAINS", "PLAINS", "BEACH", "OCEAN", "OCEAN", "OCEAN"]
id: TEMPERATE
name: "Temperate Grid"