grid:
  - ["OAK_FOREST", "BIRCH_FOREST", "SAVANNA", "SAVANNA"]
  - ["OAK_FOREST", "BIRCH_FOREST", "SAVANNA", "SAVANNA"]
  - ["TAIGA", "TAIGA", "PLAINS", "PLAINS"]
  - ["TAIGA", "TAIGA", "PLAINS", "PLAINS"]
id: TEMPERATE
name: "Temperate Grid"