blocks:
  - materials:
      - "minecraft:grass_block": 1
    layers: 1
  - materials:
      - "minecraft:white_terracotta": 2
    layers: 6
  - materials:
      - "minecraft:stone": 1
    layers: 1
id: RIDGES
name: "Sandy Palette"
simplex: true
frequency: 0.02
seed: 3