blocks:
  - materials:
      - "minecraft:grass_path": 7
      - "minecraft:grass_block": 7
      - "minecraft:grass_block": 7
      - "minecraft:grass_path": 7
      - "minecraft:grass_block": 7
      - "minecraft:grass_block": 7
      - "minecraft:grass_block": 7
      - "minecraft:white_terracotta": 1
    layers: 1
  - materials:
      - "minecraft:dirt": 7
      - "minecraft:white_terracotta": 1
    layers: 2
  - materials:
      - "minecraft:stone": 1
    layers: 1
id: RIDGES
name: "Sandy Palette"
simplex: true
frequency: 0.04
seed: 3