noise-equation: "abs(y-64)/96 + noise3(x*2, y*2, z*2)*2"
id: "NETHER"

carving:
  - CAVE: 35
  - RAVINE: 5
  - CAVERN: 5
fauna:
  FIRE:
    weight: 1
    y:
      min: 0
      max: 255

flora-chance: 60
flora-attempts: 2

ores:
  GOLD_ORE:
    min: 1
    max: 5
    min-height: 0
    max-height: 128
  QUARTZ_ORE:
    min: 3
    max: 8
    min-height: 0
    max-height: 128