noise-equation: "abs(y-64)/128 + noise3(x*2, y*2, z*2)*2"
id: "NETHER"

carving:
  - CAVE: 35
  - RAVINE: 5

ores:
  GOLD_ORE:
    min: 1
    max: 5
    min-height: 0
    max-height: 128
  QUARTZ_ORE:
    min: 3
    max: 8
    min-height: 0
    max-height: 128
  MAGMA:
    min: 1
    max: 2
    min-height: 0
    max-height: 36