blocks:
  - materials:
      - "minecraft:ice": 3
      - "minecraft:water": 2
    layers: 1
  - materials:
      - "minecraft:water": 1
    layers: 1
id: COLD_OCEAN
name: "Cold Ocean Palette"
simplex: true
frequency: 0.025