blocks:
  - materials:
      - "minecraft:kelp": 1
    layers: 1
  - materials:
      - "minecraft:kelp_plant": 1
    layers: 4

id: KELP_SHORT
name: "Short Kelp"
spawnable:
  - "minecraft:sand"
  - "minecraft:stone"
  - "minecraft:red_sand"
  - "minecraft:gravel"
  - "minecraft:dirt"
replaceable:
  - "minecraft:water"