id: CAVE
length:
  min: 20
  max: 100
start:
  x: 1
  y: 0.25
  z: 1
  radius:
    multiply:
      x: 1
      y: 1
      z: 1
    min: 1
    max: 3
  height:
    min: 4
    max: 72
mutate:
  x: 2
  y: 6
  z: 2
  radius: 0.125
palette:
  inner:
    replace-blacklist: true
    replace:
      - "minecraft:air"
      - "minecraft:water"
      - "minecraft:lava"
      - "minecraft:bedrock"
    blocks:
      - materials: {"minecraft:air": 1}
        y: 255
      - materials: {"minecraft:lava": 1}
        y: 8
  outer:
    replace-blacklist: false
    replace: []
    blocks:
      - materials: { "minecraft:stone": 1 }
        y: 255
shift:
  "minecraft:grass_block": ["minecraft:dirt"]
  "minecraft:podzol": ["minecraft:dirt"]
  "minecraft:gravel": ["minecraft:dirt"]
  "minecraft:sand": ["minecraft:dirt"]
  "minecraft:coarse_dirt": ["minecraft:dirt"]