id: "CAVE_SWAMP"
length:
  min: 20
  max: 100
start:
  x: 1
  y: 0.25
  z: 1
  radius:
    multiply:
      x: 1
      y: 1
      z: 1
    min: 2
    max: 4
  height:
    min: 4
    max: 72
cut:
  top: 0
  bottom: 0
mutate:
  x: 2
  y: 6
  z: 2
  radius: 0.125
palette:
  inner:
    replace-blacklist: true
    replace:
      - "minecraft:air"
      - "minecraft:water"
      - "minecraft:lava"
      - "minecraft:bedrock"
    blocks:
      - materials: { "minecraft:air": 1 }
        y: 255
      - materials: {"minecraft:water": 1}
        y: 48
      - materials: { "minecraft:lava": 1 }
        y: 7
      - materials: {"minecraft:obsidian": 19, "minecraft:magma_block": 1}
        y: 8
  outer:
    replace-blacklist: false
    replace:
      - "minecraft:stone"
    blocks:
      - materials: { "minecraft:stone": 21, "minecraft:spruce_wood": 1, "minecraft:dark_oak_wood": 1, "minecraft:oak_leaves[persistent=true]": 2 }
        y: 255
      - materials: { "minecraft:stone": 23, "minecraft:spruce_wood": 1, "minecraft:dark_oak_wood": 1 }
        y: 48
      - materials: { "minecraft:stone": 1}
        y: 18
  top:
    replace-blacklist: false
    replace:
      - "minecraft:stone"
    blocks:
      - materials: { "minecraft:stone": 16, "minecraft:spruce_wood": 1, "minecraft:dark_oak_wood": 1, "minecraft:oak_leaves[persistent=true]": 2 }
        y: 255
      - materials: { "minecraft:stone": 18, "minecraft:spruce_wood": 1, "minecraft:dark_oak_wood": 1 }
        y: 48
      - materials: { "minecraft:stone": 1 }
        y: 18
  bottom:
    replace-blacklist: false
    replace:
      - "minecraft:stone"
    blocks:
      - materials: { "minecraft:stone": 4, "minecraft:spruce_wood": 1, "minecraft:dark_oak_wood": 1, "minecraft:oak_leaves[persistent=true]": 2 }
        y: 255
      - materials: { "minecraft:stone": 6, "minecraft:spruce_wood": 1, "minecraft:dark_oak_wood": 1 }
        y: 48
      - materials: { "minecraft:stone": 1 }
        y: 18

shift:
  "minecraft:grass_block": ["minecraft:dirt"]
  "minecraft:podzol": ["minecraft:dirt"]
  "minecraft:gravel": ["minecraft:dirt"]
  "minecraft:sand": ["minecraft:dirt"]
  "minecraft:coarse_dirt": ["minecraft:dirt"]
update:
  - "minecraft:water"