id: RAVINE
length:
  min: 30
  max: 60
start:
  x: 1
  y: 0.0
  z: 1
  radius:
    multiply:
      x: 1
      y: 5
      z: 1
    min: 1
    max: 3
  height:
    min: 12
    max: 56
mutate:
  x: 1
  y: 3
  z: 1
  radius: 0.125
palette:
  inner:
    replace-blacklist: true
    replace:
      - "minecraft:air"
      - "minecraft:water"
      - "minecraft:lava"
      - "minecraft:bedrock"
    blocks:
      - materials: {"minecraft:air": 1}
        y: 255
      - materials: {"minecraft:lava": 1}
        y: 8
  outer:
    replace-blacklist: false
    replace: []
    blocks:
      - materials: { "minecraft:stone": 1 }
        y: 255
shift:
  "minecraft:grass_block": ["minecraft:dirt"]
  "minecraft:podzol": ["minecraft:dirt"]
  "minecraft:gravel": ["minecraft:dirt"]
  "minecraft:sand": ["minecraft:dirt"]
  "minecraft:coarse_dirt": ["minecraft:dirt"]

update: []