noise-equation: "((-((y / 63)^2)) + 1) + ((noise2(x, z)/2))"
id: "BEACH"
name: "Beach"
palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - SANDY: 64
  - GRASSY: 255
vanilla: BEACH
fauna:
  TALL_GRASS: 15
  LILY_PAD: 1
  GRASS: 70
  POPPY: 5
fauna-chance: 60

ores:
  DIRT:
    min: 0
    max: 2
    min-height: 0
    max-height: 128
  DIORITE:
    min: 0
    max: 2
    min-height: 0
    max-height: 128
  ANDESITE:
    min: 0
    max: 2
    min-height: 0
    max-height: 128
  GRANITE:
    min: 0
    max: 2
    min-height: 0
    max-height: 128
  COAL_ORE:
    min: 5
    max: 15
    min-height: 0
    max-height: 128
  IRON_ORE:
    min: 2
    max: 8
    min-height: 0
    max-height: 64
  GOLD_ORE:
    min: 1
    max: 5
    min-height: 0
    max-height: 32
  LAPIS_ORE:
    min: 1
    max: 4
    min-height: 0
    max-height: 32
  REDSTONE_ORE:
    min: 1
    max: 4
    min-height: 0
    max-height: 16
  DIAMOND_ORE:
    min: 1
    max: 2
    min-height: 0
    max-height: 16