noise-equation: "((-((y / 62)^2)) + 1) + ((noise2(x, z)+0.5) / 1.5)"
extends: "BASIC_ORES"
id: "BIRCH_FOREST"
name: "Birch Forest"

palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - SANDY: 62
  - GRASSY: 255
vanilla: BIRCH_FOREST

fauna-chance: 40
fauna:
  TALL_GRASS: 15
  GRASS: 70
  POPPY: 5

tree-chance: 100
tree-density: 7
trees:
  BIRCH: 1