noise-equation: "((-((y / 62)^2)) + 1) + ((noise2(x, z)+0.5) / 2)"
extends: "BASIC_ORES"
id: "DARK_FOREST"
name: "Birch Forest"

palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - SANDY: 62
  - GRASSY: 255
vanilla: DARK_FOREST

flora-chance: 40
flora:
  TALL_GRASS:
    weight: 15
    y:
      min: 62
      max: 255
  GRASS:
    weight: 70
    y:
      min: 62
      max: 255
  POPPY:
    weight: 5
    y:
      min: 62
      max: 255

tree-chance: 100
tree-density: 15
trees:
  DARK_OAK: 1