noise-equation: "((-((y / 62)^2)) + 1) + ((noise2(x, z)+0.5) / 3) + max(floor(noise3(x/2, y, z/2)*10 + noise2(x/2, z/2)*55)/8, 0)"
extends: "BASIC_ORES"
id: "MOUNTAINS"
name: "Mountains"

palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - TUNDRA: 100
  - SNOW: 255
vanilla: MOUNTAINS

flora-chance: 2
flora:
  SMALL_ROCK:
    weight: 1
    y:
      min: 60
      max: 72
slabs:
  enable: true
  threshold: 0.015
  palettes:
    - "minecraft:stone": "MOUNTAIN_SLABS"
    - "minecraft:snow_block": "SNOW_LAYERS"
    - "minecraft:gravel": "MOUNTAIN_SLABS"
  use-stairs-if-available: true
  stair-palettes:
    - "minecraft:stone": "MOUNTAIN_STAIRS"
    - "minecraft:gravel": "MOUNTAIN_STAIRS"