noise-equation: "((-((y / 76)^2)) + 1) + ((noise2(x, z)+0.5) / 3) + abs(noise2(x/2, z/2)*6)"
extends: "BASIC_ORES"
id: "MOUNTAINS_PRETTY"
name: "Mountains"

palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - MOUNTAIN_PRETTY: 255
vanilla: PLAINS

tree-chance: 15
tree-density: 0
trees:
  "TERRA:SPRUCE_SMALL": 7
  "TERRA:SPRUCE_MEDIUM": 3
  "TERRA:SPRUCE_LARGE": 3

flora-chance: 60
flora-attempts: 2
flora:
  SMALL_ROCK:
    weight: 1
    y:
      min: 60
      max: 72
  TALL_GRASS:
    weight: 1
    y:
      min: 2
      max: 255
  GRASS:
    weight: 5
    y:
      min: 7
      max: 255
  LEAVES:
    weight: 3
    y:
      min: 62
      max: 255
slabs:
  enable: true
  threshold: 0.015
  palettes:
    - "minecraft:stone": "MOUNTAIN_SLABS"
    - "minecraft:gravel": "MOUNTAIN_SLABS"
  use-stairs-if-available: true
  stair-palettes:
    - "minecraft:stone": "MOUNTAIN_STAIRS"
    - "minecraft:gravel": "MOUNTAIN_STAIRS"