noise-equation: "((-((y / 62)^2)) + 1) + ((noise2(x, z)+0.5) / 3) + max(floor(noise3(x/2, y, z/2)*5 + noise2(x/2, z/2)*50)/10, 0)"
extends: "BASIC_ORES"
id: "MOUNTAINS"
name: "Mountains"

palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - TUNDRA: 100
  - SNOW: 255
vanilla: MOUNTAINS

flora-chance: 2
flora:
  SMALL_ROCK: 1