noise-equation: "((-((y / 62)^2)) + 1) + ((noise2(x, z)+0.5))"
extends: "BASIC_ORES"
id: "OAK_FOREST"
name: "Oak Forest"

palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - SANDY: 62
  - GRASSY: 255
vanilla: FOREST

fauna-chance: 40
fauna:
  TALL_GRASS: 150
  GRASS: 750
  POPPY: 50
  ROSE_BUSH: 4
  LILAC: 4

tree-chance: 100
tree-density: 7
trees:
  OAK: 8
  LARGE_OAK: 2
