noise-equation: "((-((y / 62)^2)) + 1) + ((noise2(x, z)+0.5) / 1.5)"
extends: "BASIC_ORES"
id: "OAK_FOREST"
name: "Oak Forest"

palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - RIVER_BOTTOM: 61
  - RIVER_SHORE: 62
  - GRASSY: 255
vanilla: FOREST

flora-chance: 40
flora:
  TALL_GRASS:
    weight: 150
    y:
      min: 62
      max: 255
  GRASS:
    weight: 750
    y:
      min: 62
      max: 255
  POPPY:
    weight: 50
    y:
      min: 62
      max: 255
  ROSE_BUSH:
    weight: 4
    y:
      min: 62
      max: 255
  LILAC:
    weight: 4
    y:
      min: 62
      max: 255

tree-chance: 100
tree-density: 7
trees:
  OAK: 8
  LARGE_OAK: 2
