noise-equation: "-(y-62)*(y-156)*(y+25)*(y-160)*0.0000001 + if(max(y-72, 0), noise3(x, y, z)*0.75, (noise2(x, z)+0.5) / 2)"
extends: "BASIC_ORES"
id: "PLAINS_ISLANDS"
name: "Plains Islands"

palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - SANDY: 62
  - GRASSY: 255
vanilla: PLAINS

flora-chance: 60
flora:
  TALL_GRASS: 150
  GRASS: 700
  POPPY: 50
  SUNFLOWER: 8

tree-chance: 1
tree-density: 0
trees:
  "TERRA:OAK_MEDIUM": 2