noise-equation: "((-((y / 63)^2)) + 1) + ((noise2(x, z)/2))"
extends: "BASIC_ORES"
id: "RIVER"
name: "River"
palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - SANDY: 62
  - GRASSY: 255
vanilla: BEACH
flora:
  TALL_GRASS: 15
  LILY_PAD: 1
  GRASS: 70
  POPPY: 5
flora-chance: 60

carving: []