noise-equation: "((-((y / 58)^2)) + 1) + ((noise2(x, z)/2.5))"
extends: "BASIC_ORES"
id: "RIVER"
name: "River"
palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - RIVER_BOTTOM: 61
  - RIVER_SHORE: 62
  - GRASSY: 255
vanilla: RIVER
flora:
  TALL_GRASS:
    weight: 150
    y:
      min: 62
      max: 255
  LILY_PAD:
    weight: 10
    y:
      min: 62
      max: 255
  GRASS:
    weight: 700
    y:
      min: 62
      max: 255

flora-chance: 60
flora-attempts: 1