noise-equation: "((-((y / 62)^2)) + 1) + ((noise2(x, z)+0.5) / 2)"
extends: "BASIC_ORES"
id: "SAVANNA"
name: "Savanna"

palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - RIVER_BOTTOM: 61
  - RIVER_SHORE: 62
  - GRASSY: 255
vanilla: SAVANNA

flora-chance: 40
flora:
  TALL_GRASS:
    weight: 15
    y:
      min: 62
      max: 255
  GRASS:
    weight: 70
    y:
      min: 62
      max: 255

tree-chance: 80
tree-density: 1
trees:
  ACACIA: 1