noise-equation: "((-((y / 62)^2)) + 1) + ((noise2(x, z)/4))"
extends: "BASIC_ORES"
id: "SWAMP"
name: "Swamp"
palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - SWAMP_BOTTOM: 61
  - SWAMP: 255
vanilla: SWAMP
flora:
  TALL_GRASS: 150
  LILY_PAD: 40
  GRASS: 700
  BLUE_ORCHID: 20
  ROOT: 3
flora-chance: 80

carving:
  - CAVE_SWAMP: 50

tree-chance: 95
tree-density: 1
trees:
  SWAMP_OAK: 1