noise-equation: "((-((y / 62)^2)) + 1) + ((noise2(x, z)+0.5))"
extends: "BASIC_ORES"
id: "TAIGA"
name: "Taiga Forest"

palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - SANDY: 62
  - TAIGA: 255
vanilla: TAIGA

fauna-chance: 40
fauna:
  TALL_GRASS: 15
  GRASS: 70
  POPPY: 5

tree-chance: 100
tree-density: 5
trees:
  "TERRA:SPRUCE_SMALL": 7
  "TERRA:SPRUCE_MEDIUM": 3