extends: "PLAINS_ABSTRACT"
id: "TUNDRA"
name: "Tundra"

palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - TUNDRA: 255
vanilla: SNOWY_TUNDRA

fauna-chance: 2
fauna:
  SMALL_ROCK: 1