blocks:
  - materials:
      - "minecraft:grass_block": 4
      - "minecraft:stone": 1
      - "minecraft:gravel": 1
      - "minecraft:cobblestone": 1
      - "minecraft:stone": 1
      - "minecraft:grass_block": 4
    layers: 1
  - materials:
      - "minecraft:dirt": 4
      - "minecraft:stone": 1
      - "minecraft:gravel": 1
      - "minecraft:cobblestone": 1
      - "minecraft:stone": 1
      - "minecraft:dirt": 4
    layers: 1
  - materials:
      - "minecraft:stone": 1
    layers: 1
id: ROCKY
simplex: true
frequency: 0.03
seed: 4