noise-equation: "((-((y / 62)^2)) + 1) + ((noise2(x, z)+0.5) / 3)"
extends: "BASIC_ORES"
id: "MESA_BORDER"
name: "Mesa Border"

palette:
  - BEDROCK: 0
  - BEDROCK_MOST: 1
  - BEDROCK_HALF: 2
  - BEDROCK_LITTLE: 3
  - RED_DESERT_BORDER: 255
  - "BLOCK:minecraft:red_terracotta": 128
  - "BLOCK:minecraft:orange_terracotta": 124
  - "BLOCK:minecraft:terracotta": 120
  - "BLOCK:minecraft:yellow_terracotta": 116
  - "BLOCK:minecraft:red_terracotta": 112
  - "BLOCK:minecraft:orange_terracotta": 108
  - "BLOCK:minecraft:terracotta": 104
  - "BLOCK:minecraft:red_terracotta": 100
  - "BLOCK:minecraft:orange_terracotta": 96
  - "BLOCK:minecraft:terracotta": 92
  - "BLOCK:minecraft:yellow_terracotta": 88
  - "BLOCK:minecraft:red_terracotta": 84
  - "BLOCK:minecraft:orange_terracotta": 80
  - "BLOCK:minecraft:terracotta": 76
  - RED_DESERT_BORDER: 72
vanilla: BADLANDS

fauna-chance: 2
fauna:
  DEAD_BUSH: 1
  SMALL_ROCK: 1

tree-chance: 50
tree-density: 1
trees:
  CACTUS: 9
  "TERRA:DEAD": 1